### ISSUE TITLE
Have a problem in reading log_model.py

### ISSUE THREAD

**Issue by Spongesquarhead** [BEbillionaireUSD/Hades#1]
In the method forward() of Class LogEncoder:
`            if self.self_attention: log_re[:, w, :] = self.attn(seq_re)
            else: log_re[:, w, :] = seq_re[:, -1, :]
            log_re[:, w, :] = seq_re[:, -1, :] `

will the last codeline overwrite the code above make them meaningless?

**Comment by BEbillionaireUSD** [comment]
Yes. It's a typo. I've corrected it. Thanks for pointing it out.
